export { serializeSessionRecordForDisk } from "./persistence/serialize.js";
export { parseSessionRecord } from "./persistence/parse.js";
export {
  DELETION_MANIFEST_FILE_NAME,
  DeletionManifestWriteError,
  deletionManifestPath,
  describeManifestFailure,
  manifestFailureCode,
  manifestFailureRemedy,
} from "./persistence/deletion-manifest.js";
export { flushPendingSessionIndexUpdates } from "./persistence/index-update-queue.js";
export { overlaySessionIndexEntries } from "./persistence/index-overlay.js";
export type { SessionIndexEntryOverlay } from "./persistence/index-overlay.js";
export {
  DEFAULT_HISTORY_LIMIT,
  absolutePath,
  closeSession,
  countPruneCandidates,
  findClosedSessionsByDirectoryWalk,
  findGitRepositoryRoot,
  findSession,
  findSessionByDirectoryWalk,
  isArchivedRecord,
  isTemplateRecord,
  isoNow,
  listSessionIndexEntries,
  listSessions,
  listSessionsForAgent,
  listSubagentsForSession,
  matchesPruneSessionId,
  migrateTemplateSlugs,
  normalizeName,
  persistTemplateMark,
  pruneSessions,
  readPersistedLifecycle,
  resolveGlobalSessionByName,
  resolvePruneSessionIds,
  resolveSessionByExactName,
  resolveSessionRecord,
  resolveTemplateSelector,
  rollbackTemplateSlug,
  sessionBaseDir,
  sessionRecordFileName,
  writeSessionRecord,
  writeSessionRecordAtBoundary,
  writeSessionRecordAtBoundaryWithLifecycle,
  writeSessionRecordAuthorizingParent,
  writeSessionRecordAuthorizingParentWithoutIndex,
  writeSessionRecordAuthorizingSeatHolderWithoutIndex,
  writeSessionRecordWithLifecycle,
  writeSessionRecordWithPersistedLifecycle,
} from "./persistence/repository.js";
export type {
  MigrateSlugsResult,
  PersistedSessionLifecycle,
  PruneCandidateCounts,
  PruneIdResolution,
  PruneOptions,
  PruneResult,
  SessionNameCandidate,
  SessionNameResolution,
  TemplateRollbackResult,
  TemplateSelectorKind,
  TemplateSelectorResult,
  TemplateSlugAssignment,
} from "./persistence/repository.js";
// THE SEAT STORE — the authority for who holds each seat (brick b64dfbb3 / B2).
export {
  MalformedSeatRowError,
  mintSeatRow,
  mintSeatRowBestEffort,
  parseSeatFromPersisted,
  parseSeatRefOrThrow,
  parseSeatStore,
  readSeatStore,
  seatRowMissingMessage,
  SeatStoreUnhealthyError,
  seatStoreUnhealthyMessage,
  SEAT_RECORD_FIELD_PLAN,
  SEAT_STORE_FILE,
  SEAT_STORE_NO_CHANGE,
  seatFromStore,
  seatBrickLinkFromRef,
  SeatStoreUnwritableError,
  seatStorePath,
  seatToPersisted,
  withSeatStoreWrite,
} from "./persistence/seat-store.js";
export type {
  SeatBrickLink,
  SeatRecord,
  SeatStore,
  SeatStoreMutation,
} from "./persistence/seat-store.js";
